Test

diff --git a/.github/workflows/docker-publish-template.yml b/.github/workflows/docker-publish-template.yml
--- a/.github/workflows/docker-publish-template.yml
+++ b/.github/workflows/docker-publish-template.yml
@@ -63,8 +63,11 @@ jobs:
         export
         echo ${USER}
         sudo service apache2 start
-        bash .devpanel/custom_package_installer.sh
-        bash .devpanel/init.sh
+        echo "Hello" >$WEB_ROOT/index.php
+        curl -I http://127.0.0.1:80 || echo "Failed to make HTTP request to port 80"
+        
+        # bash .devpanel/custom_package_installer.sh
+        # bash .devpanel/init.sh
       env:
         APP_ROOT: '/var/www/html'        
         WEB_ROOT: '/var/www/html/web'
